blank_issues_enabled: true
contact_links:
  - name: LAN Preservation Society Discord
    url: https://discord.gg/lanpreservation
    about: Join the Discord server to chat with the community directly.
